name: DirectionalSchem
version: '1.0-SNAPSHOT'
main: net.legendahlupa.com.directionalschem.DirectionalSchem
api-version: 1.18
depend: [ Towny, WorldEdit ]
authors: [ LegendaHluPa, ReLifeTeam ]
commands:
  dirschem:
    description: "Основная команда плагина"
    permission: DirectionalSchematic.paste
    permission-message: §4У вас недостаточно прав
    usage: "Использование команды: /dirschem [File name]"
    aliases:
      - ds
permissions:
  DirectionalSchematic.paste:
    description: "Доступ к команде вставки"
    default: op
  DirectionalSchematic.*:
    description: "Доступ ко всем командам плагина"
    default: op
    children:
      DirectionalSchematic.paste: true